name: build-test-deploy
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MY_NAME: "Robsullainen"
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "$(cat hello_world.txt)"
      - name: use node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm install
      - run: npm run build
      - run: echo "env:$MY_NAME"
      
